### PR TITLE
Temporary fix for routing commands

### LINKED ISSUE #5: router:debug returns an exception
Running php app/console router:debug does not work as expected:

```
 [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                             
  Warning: strpos(): Empty needle in /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerNameParser.php line 94
```

I narrowed down the issue to ControllerNameParser::build(). The $controller parameter is resolved to:

```
web_profiler.controller.profiler:toolbarAction
...
web_profiler.controller.exception:showAction
...
Sensio\Bundle\DistributionBundle\Controller\ConfiguratorController::checkAction
...
\Controller\Report\Api\TemplateController::indexAction
```

The last controller is located in src/Controller/Report/Api/TemplateController.php

I was not able to narrow it down any further however, since I can't seem to find the line where build() is actually called from.

### PR DESCRIPTION
**Pull request by zebba**
This temporary closes WouterJ/Bundleless#5

### CODE REVIEW

File: Controller/ControllerNameParser.php [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+class ControllerNameParser extends BaseControllerNameParser
+{
+    public function build($controller)
+    {
+        if ('\\' === substr($controller, 0, 1)) {
+            $controller = substr($controller, 1);
+        }
+
+        return parent::build($controller); // TODO: Change the autogenerated stub
```
Comment (wouterj) [inline Controller/ControllerNameParser.php]: you should remove the comment, it's no longer an autogenerted stub

File: Controller/ControllerNameParser.php [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+    }
+
```
Comment (wouterj) [inline Controller/ControllerNameParser.php]: you should remove this line

**Comment by wouterj** [comment]
I would rather see getting this fixed in Symfony itself. But I can live with a temporary fix :)
